  0% 0/42087 [00:00<?, ?it/s]/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:749: UserWarning: Note that order of the arguments: ceil_mode and return_indices will changeto match the args list in nn.MaxPool2d in a future release.
  warnings.warn("Note that order of the arguments: ceil_mode and return_indices will change"
  0% 0/42087 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/ws/external/train_VIGOR.py", line 186, in <module>
    model_dir = f'/ws/external/checkpoints/models/VIGOR/{area}/{args.save}/' + str(epoch) + '/'
AttributeError: 'dict' object has no attribute 'save'
Evaluation on validation set